### ISSUE TITLE
Event handlers pile-up

### ISSUE THREAD

**Issue by dynamodan** [walterhiggins/ScriptCraft#174]
My son and I were experimenting with events using a statement like this:

var newListener = events.on('player.PlayerInteractEvent', function (evt) { ... });

I was doing this in the "classroom" setting, where every time the file is saved, the ScriptCraft plugin reloads the *.js file that had just been edited.  This was causing a new event listener to be registered, and the old one was still there.  So after n edits, there would be n+1 event listeners registered, between saves (assuming the events.on() call was successful in registering a new event).

Outside of the classroom (i.e. in the plugins folder where arrows.js lives), this problem wouldn't be noticed *unless* the `js refresh()` command was run in the server's operator console.  Then the problem is the same--every refresh will cause an accumulation of event handlers, because they are getting stored in the bukkit server itself, which persists across the ScriptCraft reloads.  Only if the entire server is restarted, do the accumulated handlers get cleared out.

I'm not sure what the solution is, but I'm inclined toward a method of storing a table of ScriptCraft-generated event handlers, so that, in the very least, a `js refresh()` method clears out only those handlers that were registered by calls to events.on() from ScriptCraft.  Or at the most, the same storage table would enable a previously registered handler to be replaced by a subsequent call to events.on() to a handler of the same name.

**Comment by walterhiggins** [comment]
Hey @dynamodan,

I've updated the classroom module so that event listeners added for any given player will be unregistered when that player's modules are reloaded. This should be in the next release of ScriptCraft (3.1.1)
