### ISSUE TITLE
Consider Minetest

### ISSUE THREAD

**Issue by nixnax** [walterhiggins/ScriptCraft#195]
ScriptCraft is amazing...  
However, the open source server issue continues to hang over it's head.
So I got thinking, maybe add it to the open source http://minetest.net?
Only problem is, the minetest devs are pretty adament on LUA.

**Comment by nixnax** [comment]
Or fork minetest :)

**Comment by nixnax** [comment]
Or provide a "hybrid" where you can combine elements from canary, voxel.js and https://github.com/deathcap/voxel-plugins/wiki to migrate between mc and voxel.js

**Comment by nixnax** [comment]
Looks like some work has been done:
https://github.com/brettlangdon/NodeLua

**Comment by walterhiggins** [comment]
Hi @nixnax 
For the foreseeable future - given limited resources - ScriptCraft will be Minecraft-only and Javascript-only.
