### ISSUE TITLE
Support for building script into independent plugin

### ISSUE THREAD

**Issue by samkass** [walterhiggins/ScriptCraft#201]
I was encouraging my kids to get back to ScriptCraft last night, and they were hesitant because they wanted to write a "real" plugin that could be distributed in one of the plug-in repositories.  Then I was thinking that there's no reason a scriptcraft plugin couldn't be made "real" if it took someone's script, bundled it with the "runtime" (plugin, existing scripts, and configuration to tell it to find the scripts within the .jar) into a jar, and distributed it.  Have any of the developers tried it or know of any major roadblocks?  It seems like relatively small changes to the scriptcraft loader to look within its own jar for a config file telling it where to find the scripts directory (external or internal) would get you 90% of the way there.  If no one's tried it I'll give it a whirl when a get a chance.

**Comment by samkass** [comment]
(Hm, might also have to think about how two separate scriptcraft-bundled installed plugins would interact.)

**Comment by walterhiggins** [comment]
Hey @samkass ,
This sounds like a great idea - I'd start by looking at ScriptCraft's build.xml file - You're right, there's no reason someone couldn't use ScriptCraft to create their own redistributable SpigotMC or CanaryMod plugin. 
It's kind of outside of the scope of ScriptCraft itself though so I'd recommend forking and creating a wrapper project.
