### ISSUE TITLE
Using Vault with ScriptCraft

### ISSUE THREAD

**Issue by NathanFlurry** [walterhiggins/ScriptCraft#205]
Hello,

I've been researching this for a couple hours now, and I can't seem to figure out how to import Vault and use it in ScriptCraft. I've looked at using `importPackage()` and I know I need to import `net.milkbowl.vault.economy.Economy`, but I haven't figured much else from there.

Thanks,
Nathan

**Comment by walterhiggins** [comment]
Are you using Bukkit or CanaryMod?

**Comment by NathanFlurry** [comment]
Sorry, I forgot to specify: I'm using Bukkit, but I hope to eventually start a server completely based on ScriptCraft with CanaryMod.

Thanks for the quick reply!

**Comment by walterhiggins** [comment]
Hi @NathanFlurry ,

You can access the Plugin's API once you get the plugin by its name:

http://dev.bukkit.org/bukkit-plugins/scriptcraft/?page=2#c49

**Comment by NathanFlurry** [comment]
Thanks! I seem to have missed that.
