### ISSUE TITLE
YPGPM and CanaryMod: monster config not working as advertised

### ISSUE THREAD

**Issue by carlrobert** [walterhiggins/ScriptCraft#224]
These three need updating. If I find the solution, I'll be back with a pull request.
/js self.location.world.allowMonsters
/js self.location.world.allowMonsters = true
/js self.location.world.setSpawnFlags(false, true)

(spawn-monsters=true mentioned in the CanaryMod config docs)

**Comment by walterhiggins** [comment]
Changed this section to use world.raining instead.
