### ISSUE TITLE
Frequently-Asked-Questions.md and Using-Java-APIs-In-Javascript.md unused?

### ISSUE THREAD

**Issue by carlrobert** [walterhiggins/ScriptCraft#227]
Frequently-Asked-Questions.md and Using-Java-APIs-In-Javascript.md seem not to be used for document generation. I'm probably missing something obvious here?

https://github.com/walterhiggins/ScriptCraft/blob/d0e919db19a4425e88f01ea21efac79a353e0ee2/docs/Frequently-Asked-Questions.md

https://github.com/walterhiggins/ScriptCraft/blob/d0e919db19a4425e88f01ea21efac79a353e0ee2/docs/Using-Java-APIs-In-Javascript.md

**Comment by walterhiggins** [comment]
Hi @carlrobert ,

You're right. They're not used for generating the API reference and Young Person's guide. They're stand-alone documents in their own right.

**Comment by carlrobert** [comment]
Hi Walter,

Trying to improve my question :), I'm not sure about the discoverability of these documents. They don't seem to be linked to from anywhere. Would it make sense to refer to them from the YPGPM or the API spec?

Best regards,
Robert
