### ISSUE TITLE
Getting a bunch of exceptions when trying to draw a sphere

### ISSUE THREAD

**Issue by AndersBillLinden** [walterhiggins/ScriptCraft#238]
After I have started the server with 

````
C:\canarymod>java -Xmx1024M -Xms1024M -jar CanaryMod-1.8.0-1.2.0-RC1.jar nogui
````

and written 

````
/js sphere( blocks.iron, 10);
````

I was getting the following exception:

````
[22:25:59] [ScriptCraft] [ERROR]: Error while trying to evaluate javascript: sph
ere( blocks.iron, 10);, Error: JavaException: javax.script.ScriptException: sun.
org.mozilla.javascript.internal.EvaluatorException: Java constructor for "net.ca
narymod.LineTracer" with arguments "net.canarymod.api.CanaryServer" not found. (
<Unknown source>#293) in <Unknown source> at line number 293
````

**Comment by walterhiggins** [comment]
Which version of java are you using?

**Comment by AndersBillLinden** [comment]
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

and I also tried the 32 bit
java version "1.7.0_80-ea"
Java(TM) SE Runtime Environment (build 1.7.0_80-ea-b05)
Java HotSpot(TM) Client VM (build 24.80-b07, mixed mode, sharing)

**Comment by carlrobert** [comment]
Hi Anders,

Have you tried upgrading to the 1.2.0 release of CanaryMod? http://canarymod.net/releases/canarymod-120

**Comment by AndersBillLinden** [comment]
Yes, the same result

**Comment by AndersBillLinden** [comment]
Yes, with the same result.

**Comment by walterhiggins** [comment]
Hey @AndersBillLinden 

Do you run the `/js sphere( blocks.iron, 10);` statement at the server console window or at the in-game prompt? Any Drone functions (such as sphere, box etc) will only work if:

1. Invoked by a player at the in-game prompt or ...
2. Invoked on a Drone object which has been constructed with a player as a constructor parameter e.g.
```javascript
var d = new Drone( player ) ; // assumes player is a reference to a Player object
d.sphere( blocks.iron, 10);
```
I suspect you might be trying to run the `/js sphere( blocks.iron, 10)` statement from the server console window. Let me know if this isn't the problem.

**Comment by AndersBillLinden** [comment]
I did it in the console. Getting "unknown command" if trying to do it from the ingame prompt (the one that pops up when I press T).

**Comment by walterhiggins** [comment]
Hey @AndersBillLinden 
Make yourself an operator in the console window and then the /js command should be available to you.
In the console window: `operator <your-name>`
In the in-game prompt: `/js sphere(blocks.iron, 10);`
