### ISSUE TITLE
Teleport seems to be broken in 3.1.4 on canary

### ISSUE THREAD

**Issue by gingemonster** [walterhiggins/ScriptCraft#244]
Im a noob to this mod but a programmer, I cannot get arrows.teleport() to actual teleport. All the other version of arrows work but not teleporting. I tried my own script for teleporting and this didnt work either?

**Comment by gingemonster** [comment]
I took the code changes from https://github.com/walterhiggins/ScriptCraft/issues/215 manually and its working guess thats it and waiting on a new full release

**Comment by walterhiggins** [comment]
Hi,
Can you tell me which version of Java and which OS you were using? I'd like to post a fix for this that works across all platforms / java versions.
Walter

**Comment by gingemonster** [comment]
using windows 8.1 java 7 (not sure exact sub version Ill check later)
