### ISSUE TITLE
arc not drawing depending on block type used

### ISSUE THREAD

**Issue by gingemonster** [walterhiggins/ScriptCraft#245]
if I type:

arc({blockType: blocks.wool.black, meta: 0, radius: 8,strokeWidth: 1} );

it doenst draw an arc but if I type

arc({blockType: blocks.wool.white, meta: 0, radius: 8,strokeWidth: 1} );

it does?

**Comment by walterhiggins** [comment]
I'll take a look

**Comment by walterhiggins** [comment]
Hi @gingemonster ,

The arc() function is a low-level drone function. It's called by sphere, cylinder etc.
The parameter's blockType and meta should be a block id and meta information.
If you want to build black wool I recommend:

```javascript
arc( { blockType: 35, /* wool */ meta: 15 /* black */, radius: 8, strokeWidth: 1} );
