### ISSUE TITLE
It's possible to create a GUI?

### ISSUE THREAD

**Issue by codejam1024** [walterhiggins/ScriptCraft#252]
It's possible to create a GUI?

**Comment by TechplexEngineer** [comment]
Generally the answer would be no as most GUI's people think of require client mods. If you mean abusing the chest or some other item that has inventory to make a "GUI" then, then answer would be probably. This may help: https://bukkit.org/threads/tutorial-create-a-inventory-menu.173571/

**Comment by ellisgl** [comment]
codejam1024 did you get that to work? If so, can we see your code?

**Comment by 808dkaneohe** [comment]
You can use scoreboards or JSONS to make a gui

**Comment by ellisgl** [comment]
808dkaneohe,

When I think of GUI, I think of the something dialog selection - like in RPGs.

**Comment by demipixel** [comment]
- If you want a scoreboard, look at the docs for scoreboards. If you need different users to have different info, use [NMS](https://bukkit.org/threads/packetplayout-constructors.397793/) so you can send different data to different users.
- If you are talking about chat, you'll need to use some kind of existing library or use NMS to send the json manually (not ideally recommended, depends on what you need.
- If you're looking for some kind of fake opened chest to select items, you'll need `server.createInventory` to create an inventory to send to the player. Most of this is just looking at the spigot docs to see how to add items and send the inventory to the player. Use inventory events to check if it's the inventory you sent them, cancel whatever they're trying to do, and then perform the correction action (teleport them, send them to the server, send a chat message, whatever)

I think it's about time we close this issue.

**Comment by TonyGravagno** [comment]
Closing. This discussion can be continued in the Google Group, where I hope anyone interested will provide more info about exactly what they want to do so that others can provide very specific answers.
