### ISSUE TITLE
how do I make an explosion? 

### ISSUE THREAD

**Issue by x13machine** [walterhiggins/ScriptCraft#259]
I tried self.world.makeExplosion(). It gave me some weird error.

**Comment by walterhiggins** [comment]
Try this instead (to create an explosion at your own location):

```javascript
var loc = self.location;
var yield = 2.5; // standard yield for primed TNT
self.world.makeExplosion(self, loc.x, loc.y, loc.z, 2.5, true);
```
http://docs.visualillusionsent.net/CanaryLib/1.2.0/net/canarymod/api/world/World.html#makeExplosion(net.canarymod.api.entity.Entity,%20double,%20double,%20double,%20float,%20boolean)

**Comment by x13machine** [comment]
good way to crash the server

**Comment by walterhiggins** [comment]
Hi @x13machine , can you elaborate? I tried the above code myself and the server did not crash.

**Comment by x13machine** [comment]
explosion of 10,000 crashes the server
