### ISSUE TITLE
Can I use java libraries or something?

### ISSUE THREAD

**Issue by x13machine** [walterhiggins/ScriptCraft#260]
I wanted to connect to a redis database. Would I be able to use java libraries or node.js modules?

**Comment by walterhiggins** [comment]
You should be able to use Java libraries if there are java bindings for redis.

**Comment by x13machine** [comment]
where would I put the .jar file for the redis library?

**Comment by x13machine** [comment]
I figured it out.

**Comment by x13machine** [comment]
a

**Comment by x13machine** [comment]
In java to connect a redis database it would be new Jedis("localhost"); I did /js c=new java.Jedis('localhost') . It complained that jedis is an object.

**Comment by walterhiggins** [comment]
What java package does the Jedis class live in? The code should be something like:
```
/js var jedis = new redis.clients.jedis.Jedis('localhost')
```

**Comment by walterhiggins** [comment]
If you need to use redis (or any other Java library) , include the jar file in the classpath when starting the server.

`java -cp redis.jar:spigotmc.jar -org.bukkit.craftbukkit.Main` (or whichever Main class is used by spigotmc or CanaryMod)
