### ISSUE TITLE
setInterval gives javascript error with the new spigot 1.8

### ISSUE THREAD

**Issue by pfigueiredo** [walterhiggins/ScriptCraft#267]
Error:
Can't find method org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(org.scriptcraftjs.bukkit.ScriptCraftPlugin,sun.org.mozilla.javascript.Undefined,number,number)

**Comment by walterhiggins** [comment]
I can't reproduce with Spigot 1.8.8

**Comment by LionWaffles** [comment]
Did you try running using CanaryMod?

**Comment by walterhiggins** [comment]
I've tried to reproduce this with Spigot 1.9 and cannot reproduce the issue.
