### ISSUE TITLE
ScriptCraft Multiple Instances

### ISSUE THREAD

**Issue by Pecacheu** [walterhiggins/ScriptCraft#268]
Ever since Bukkit/Spigot 1.8, scriptcraft has been acting really weirdly. First of all, when you start the server, event handlers don't work until someone joins and calls '/js refresh()' at least once in game. I tried using ConsoleScheduler plugin to call it 30 seconds after the server is done loading, but it says "unknown command js", even though the js command works fine in the console. Second, the more times you refresh scriptcraft, the more instances pile up. It can get so bad, people can see "Welcome to scriptcraft. Welcome to scriptcraft..." 30 times in a row when they join. Worst of all, event handers, intervals, and scheduled actions don't get removed after a refresh like they should. In fact, they don't even get removed after a server-wide '/reload'! The only way to properly reset scriptcraft is '/stop' and restarting.

Is anyone else having these problems with scriptcraft on Bukkit/Spigot 1.8?

**Comment by Pecacheu** [comment]
Um... Is anyone ever going to respond to this?

**Comment by arvin1209** [comment]
yes

On Fri, Sep 25, 2015 at 10:43 PM, Bryce <notifications@github.com> wrote:

> Um... Is anyone ever going to respond to this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/walterhiggins/ScriptCraft/issues/268#issuecomment-143392864>
> .
>



-- 

Arvin Singh or Avi Singh

**Comment by arvin1209** [comment]
same with me


On Sat, Sep 26, 2015 at 7:21 PM, Science Asap <curiousme.avi@gmail.com>
wrote:

> yes
>
> On Fri, Sep 25, 2015 at 10:43 PM, Bryce <notifications@github.com> wrote:
>
>> Um... Is anyone ever going to respond to this?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/walterhiggins/ScriptCraft/issues/268#issuecomment-143392864>
>> .
>>
>
>
>
> --
>
> Arvin Singh or Avi Singh
>
>


-- 

Arvin Singh or Avi Singh

**Comment by walterhiggins** [comment]
What's the exact version of SpigotMC you're using?

**Comment by walterhiggins** [comment]
What's the exact version of SpigotMC you're using?

**Comment by Pecacheu** [comment]
I currently have version 3.1.10 running on Spigot 1.8.3. That may be a little out of date, I've been on vacation.

**Comment by MrVoltz** [comment]
This is fixed in my PR #284.
