### ISSUE TITLE
Always extracts plugins/modules/libs

### ISSUE THREAD

**Issue by optimusbrine** [walterhiggins/ScriptCraft#271]
From the documentation it looks like plugins/ modules/ and libs/ are only supposed to get extracted when a new version of the plugin is installed, but for me it happens on every single restart if I do not set the appropriate setting in config.yml

Is this intended behavior? It was very surprising installing the plugin for the first time, clearing out the example plugins and having them show back up when restarting.

**Comment by walterhiggins** [comment]
Hi @optimusbrine ,

Yes it's intended behavior. You can disable it by updating the flags in config.yml See #102

Walter
