### ISSUE TITLE
/js bed() no longer works

### ISSUE THREAD

**Issue by kellyfj** [walterhiggins/ScriptCraft#276]
```
[19:36:16] [CanaryMod] [INFO]: Command used by CoderDojo2: /js bed();
[19:36:16] [ScriptCraft] [INFO]: Drone build error: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.runtime.NativeJavaPackage to java.lang.Comparable while processing function wrapperFn() { [native code] }
```

ENVIRONMENT
Jars
```
CanaryMod-1.8.0-1.2.0-RC1.jar
```
and ScriptCraft.jar from http://scriptcraftjs.org/download/latest/scriptcraft-3.1.10/

```
$ java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)
```

```
system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.10.5 (14F27)
      Kernel Version: Darwin 14.5.0

```

**Comment by walterhiggins** [comment]
Hey @kellyfj ,

I don't have that exact machine configuration myself but I haven't been able to reproduce this problem with either of the following Java versions on Mac OS X
```
java version "1.7.0_60-ea"
Java(TM) SE Runtime Environment (build 1.7.0_60-ea-b02)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b04, mixed mode)
```
or java 1.8
```
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```
I'm still on OS X Yosemite 10.10.4 . I'll try to reproduce it again once I've upgraded.

**Comment by kellyfj** [comment]
Hey Walter - FYI when I used this version of CanaryMod it works fine
```CanaryMod-1.8.0-1.2.1-SNAPSHOT-shaded.jar	```
I get that from here http://scriptcraftjs.org/download/latest/

Perhaps we just need to update the Canary Mod install instructions here
https://github.com/walterhiggins/ScriptCraft/blob/master/docs/YoungPersonsGuideToProgrammingMinecraft.md#installation

Also FYI the link in that documentation (https://canarymod.net/books/canarymod-admin-guide) is now a 404

Thanks!

**Comment by walterhiggins** [comment]
Thanks @kellyfj,
I've mirrored the canarymod docs here https://github.com/walterhiggins/canarymod-admin-guide/
