### ISSUE TITLE
link to CanaryMod install instructions returns a 404

### ISSUE THREAD

**Issue by bengolder** [walterhiggins/ScriptCraft#281]
The link seems to be broken and I'm not sure what the right replacement would be.

https://github.com/walterhiggins/ScriptCraft/blob/master/docs/YoungPersonsGuideToProgrammingMinecraft.md

```
1. [Download and install CanaryMod][dlcm] then follow the [CanaryMod
   Installation Instructions][cmadmin]. 

[cmadmin]: http://canarymod.net/books/canarymod-admin-guide
```

**Comment by walterhiggins** [comment]
I've just created a repo for the Canarymod Admin Guide (it's no longer hosted on the canarymod site)

https://github.com/walterhiggins/canarymod-admin-guide
