### ISSUE TITLE
PlayerInteractEvent with air

### ISSUE THREAD

**Issue by tjhgit** [walterhiggins/ScriptCraft#287]
am trying to catch an event when the player interacts with air:

var evt1 = org.bukkit.event.player.PlayerInteractEvent;
events.on(evt1,my_evt_handler);

I found how to solve this:

in lib/events-bukkit.js

change this line:
regd = new bkRegisteredListener( __plugin, eventExecutor, priority, __plugin, true );

to:
regd = new bkRegisteredListener( __plugin, eventExecutor, priority, __plugin, false );

Does this make sense to you? Then please change this on github.

See also:
https://github.com/walterhiggins/ScriptCraft/issues/256

**Comment by walterhiggins** [comment]
Will be fixed in the next release.
