### ISSUE TITLE
Missing blocks?

### ISSUE THREAD

**Issue by Sasha91** [walterhiggins/ScriptCraft#288]
hey.

I'm fiddling around with scriptcraft quite a bit, and also teaching it to kids as a volunteer.

There seems to be a problem with placing some bricks.
like blocks.brick.stone, blocks.brick.mossy and blocks.brick.cracked all just places the blocks.brick.stone block, when used as a parameter in the box() method.

this problem occurs with several other blocks as well, the same issue where it only places one veriant of a block.

Am i doing something wrong? a special version of canarymod needed or something?
I'm using the version of scriptcraft and canarymod that is available at http://scriptcraftjs.org/ in the moment of writing.

**Comment by jbforth4** [comment]
I tried the same thing and got the same results. If you use the number reference it works. For example using '48' instead of brick.mossy. Hope that helps

**Comment by Sasha91** [comment]
I tried it with the brick.mossy, it's 98:3 or something, which have to be passed as a string, still i couldn't get it to work. but thanks for the comment. Scriptcraft works perfectly with spigot though, which is what i'll switch to.

**Comment by walterhiggins** [comment]
@Sasha91 I reckon this must be an issue with that particular version of CanaryMod.
