### ISSUE TITLE
Please modify text in Prerequisites - CanaryMod not required

### ISSUE THREAD

**Issue by CleanerOrc** [walterhiggins/ScriptCraft#296]
Hi, would you please modify the Prerequisites section to match what you say later in the text, that the plugin will work with any of the server mods listed.

It's really confusing to read that CanaryMod is a prereq.  You almost have to search through the whole descrip page to finally learn that it will work with most of the available server mods.

Also, IMHO, the Spigot server mod seems to be carrying the torch pretty well after the Bukkit demise, so it's even more confusing to see that CanaryMod is a prereq.

BTW, AM GRATEFUL for the ScriptCraft!!!!

**Comment by walterhiggins** [comment]
Thanks @CleanerOrc . I've updated the README.md so that SpigotMC is the recommended platform.
