### ISSUE TITLE
Hoping a little bit of help will go a long way

### ISSUE THREAD

**Issue by dropbear42** [walterhiggins/ScriptCraft#305]
Hi Walter,

SLOWLY making progress with Scriptcraft/CanaryMod.

Hoping you can help us speed things up. Any tips for better ways to debug. At the moment I'm using LOTS of echos, but echo only seems to work after at least one js command has been entered in the console. E.g. if I add an echo to the stealthcookies.js plugin, nothing happens until I've run a command for another plugin (e.g. js arrows)

Another issue we've run into is attempting to allow flight. Pretty sure we're doing it correctly by calling the setMayFly method on the HumanCapabilities object, but no joy. Even your /js self.allowFlight = true ; is not doing anything.

Finally, a number of events don't appear to be firing. E.g. events.itemUse() is working fine, but events.heldItemChange() and events.itemPickup() don't appear to fire.

Love the concept of ScriptCraft but at this point very few of the plugins/commands actually seem to work as intended. Hoping it's all user error and can be rectified with a small amount of help.

Cheers
Stephen

**Comment by walterhiggins** [comment]
> Another issue we've run into is attempting to allow flight. Pretty sure we're doing it correctly by calling the setMayFly method on the HumanCapabilities object, but no joy. Even your /js self.allowFlight = true ; is not doing anything.

I've just tried this and it works as advertised. If you double-press the space bar, you should be able to fly.

**Comment by walterhiggins** [comment]
> Finally, a number of events don't appear to be firing. E.g. events.itemUse() is working fine, but events.heldItemChange() and events.itemPickup() don't appear to fire.

I'm not sure what I can do regarding these events - they are specific to CanaryMod and as far as I know, CanaryMod is no longer in active development - I'd recommend using the SpigotMC/Bukkit events instead https://github.com/walterhiggins/ScriptCraft/blob/development/docs/API-Reference.md#events-helper-module-spigotmc-version

**Comment by walterhiggins** [comment]
Have you considered using SpigotMC instead of CanaryMod?
