### ISSUE TITLE
Plugin creates plugins folder then warns about it

### ISSUE THREAD

**Issue by TonyGravagno** [walterhiggins/ScriptCraft#306]
Delete the server folder /plugins/scriptcraft.
Start the server. The plugin recreates it.
The console then displays:

> WARN Please put plugins in the /scriptcraft/plugins directory
> WARN Legacy ScriptCraft directory /plugins/scriptcraft was found. This directory is no longer used.

Please eliminate this folder creation which adds a new default config.yml.

**Comment by jamesjryan** [comment]
Yeah + 1 this is an annoying warning, but not a huge deal.

**Comment by walterhiggins** [comment]
I'm going to remove the warning message - the plugin folder is created by spigotmc/bukkit - not by scriptcraft.
