### ISSUE TITLE
Warning: updater could not find any files for the project id 31279

### ISSUE THREAD

**Issue by TonyGravagno** [walterhiggins/ScriptCraft#309]
What is this error, and can/should it be eliminated?

>[Server] INFO Please note that the working directory for scriptcraft v3.2.0-2016-03-19 is /scriptcraft
>[Server] WARN Please put plugins in the /scriptcraft/plugins directory
>[Server] WARN Legacy ScriptCraft directory /plugins/scriptcraft was found. This directory is no longer used.
>[Server] WARN cow-clicker minigame is not yet supported in CanaryMod or Craftbukkit
>[Server] WARN Could not connect to dev.bukkit.org, please try again later.
>[Server] WARN :1:1: Premature end of file.
>[Server] INFO No updates found!
>[Server] WARN The updater could not find any files for the project id 31279
>[Server] INFO Enabling scriptcraft v3.2.0-2016-03-19

**Comment by walterhiggins** [comment]
I've never seen this message: `The updater could not find any files for the project id 31279`

**Comment by TonyGravagno** [comment]
All of these pages indicate this is an issue with Update routines that seem to be looking for an update from their home site, a Bukkit site, etc.. Given the other error about dev.bukkit.org and the confirmation for "No updates found!", I'm guessing it's related to that.
HTH

http://www.minecraftserverhost.net/forum/viewtopic.php?t=1710&p=3479
https://github.com/PEXPlugins/PermissionsEx/issues/2495
https://github.com/games647/LagMonitor/issues/12

**Comment by jonathanperret** [comment]
This message is generated by an updater running in the `PermissionsEx` plugin (see https://github.com/PEXPlugins/PermissionsEx/issues/2495 , and for the specific line of code: https://github.com/gravitylow/Updater/blob/a857fd9/src/main/java/net/gravitydevelopment/updater/Updater.java#L677). It has nothing to do with ScriptCraft, so I believe this issue and #308 can be closed.

**Comment by TonyGravagno** [comment]
Agreed. Thanks!!
