### ISSUE TITLE
Event Object

### ISSUE THREAD

**Issue by grimmdev** [walterhiggins/ScriptCraft#314]
I'm essentially curious how to get all the keys and values of the event object. I tried a few javascript methods which didn't workout and the utils.foreach. Is there a way to loop through the event object to get the keys and values available?

**Comment by walterhiggins** [comment]
```javascript
var evtFn;
for (evtFn in events){
   console.log( evtFn.name );
}
```

**Comment by grimmdev** [comment]
Thank you walter, I also wanted to say good work, I love the plugin so far. I already started making things and stuff with it.
