### ISSUE TITLE
Store Drone Coords to variable

### ISSUE THREAD

**Issue by 808dkaneohe** [walterhiggins/ScriptCraft#325]
Sorry if this is a noob question but I was looking to make a kitpvp game where at the end of a round players teleport to the generated spawn area.

Is there a way to save drone checkpoint or coords as to teleport the play back.

Thanks!

**Comment by softwaremaverick** [comment]
As per my pull request the drones variables are x, y, and z. I believe you can access these but not confirmed. However it sounds like you just want spawn coordinates not done unless I misunderstood you.

On 21 February 2017 04:59:38 GMT+00:00, Diego Eann <notifications@github.com> wrote:
>Sorry if this is a noob question but I was looking to make a kitpvp
>game where at the end of a round players teleport to the generated
>spawn area.
>
>Is there a way to save drone checkpoint or coords as to teleport the
>play back.
>
>Thanks!
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/walterhiggins/ScriptCraft/issues/325

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 808dkaneohe** [comment]
To clarify what I was thinking was that I could save the respective drone xyz to variables as to later teleport the players there

**Comment by softwaremaverick** [comment]
drone.x drone.y and drone.z should be accessible to you from outside the object.



On 22 February 2017 02:56:52 GMT+00:00, Diego Eann <notifications@github.com> wrote:
>To clarify what I was thinking was that I could save the respective
>drone xyz to variables as to later teleport the players there
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/walterhiggins/ScriptCraft/issues/325#issuecomment-281553801

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by 808dkaneohe** [comment]
@softwaremaverick okay thanks!
