### ISSUE TITLE
How to move a player ?

### ISSUE THREAD

**Issue by weilantian** [walterhiggins/ScriptCraft#334]
I didn't find a function to move a player.

**Comment by cwinsloweaton** [comment]
[This section](https://github.com/walterhiggins/ScriptCraft/blob/development/docs/API-Reference.md#teleport-module) of the documentation might be what you're looking for!

**Comment by TonyGravagno** [comment]
I'm closing this as answered. If more detail is required, please start a new ticket with more detail about exactly what you want to do:

- Move the current player?
- Move another player?
- Move arms or legs?
