### ISSUE TITLE
JavaScript code formatting

### ISSUE THREAD

**Issue by TonyGravagno** [walterhiggins/ScriptCraft#347]
I believe consistent code formatting of the JavaScript will be helpful to students trying to read the code, following the indentations and braces, etc. I'd like to submit a new PR for this ticket with nothing but this reformatting just to get all code items to follow one style.

I'm formatting with the common [JS Beautifier](https://github.com/beautify-web/js-beautify) tool. This was originally ported into NetBeans in a prior version but it didn't work. Just for this ScriptCraft project I've [forked that code and fixed it](https://github.com/TonyGravagno/netbeans-jsbeautify), for single keystroke formatting.

I've already done this in my repo, I'd just like to PR it.

**Comment by walterhiggins** [comment]
See https://github.com/walterhiggins/ScriptCraft/blob/development/contributing.md#coding-conventions. 
Please don't apply tooling across the entire codebase.
