### ISSUE TITLE
Update for Minecraft 1.12.2

### ISSUE THREAD

**Issue by TonyGravagno** [walterhiggins/ScriptCraft#348]
Requires rebuild with latest Spigot.

**Comment by jonathanperret** [comment]
I believe it doesn’t require a rebuild, actually.

**Comment by TonyGravagno** [comment]
I just entered this ticket to document the update - I needed to enter some text in the box. ;)

**Comment by jonathanperret** [comment]
I guess my point was (I was on my phone, sorry for the terse message), I don't believe there is anything to be done in ScriptCraft to support Minecraft 1.12.2. Hence my puzzlement at the very existence of this ticket 🤔

**Comment by jonathanperret** [comment]
Contradicting myself, I just submitted #350 which updates the Spigot JAR to 1.12.2, and does bring a couple new events when compared with the previously used 1.11.2. I guess I was thinking of the 1.**12**.1 to 1.12.2 migration which contains no API changes.

**Comment by walterhiggins** [comment]
Release 3.3.0 includes 1.12.2 support.
