### ISSUE TITLE
Can't create object location

### ISSUE THREAD

**Issue by unpluggedLink** [walterhiggins/ScriptCraft#357]
I want to create a location object like you can in java. example

Location location = new Location(world, x, y, z)

been searching for days with no luck please help me walter

**Comment by walterhiggins** [comment]
```javascript
// to create a new location x:1, y:2, z:3 at the server's main world...
var location = new org.bukkit.Location(server.worlds[0], 1, 2, 3);
```
Hope this helps

**Comment by unpluggedLink** [comment]
Thank you very much, I'm in love with your API, hopefully I'll help you maintain in it the future. You are even answering requests so fast, Congratulations man you are awesome
