### ISSUE TITLE
Own requires? (fs, path, ...)

### ISSUE THREAD

**Issue by Meldiron** [walterhiggins/ScriptCraft#358]
Hello,
there are a lot of modules on NPM I can get and use in NodeJS.
If I try to run:
/js var fs = require('fs')
I get an error. Can I somehow install NPM modules?

**Comment by SEAPUNK** [comment]
SC is not a Node.js runtime. You don't get any of the modules in Node.js or NPM for ScriptCraft, because they're not compatible with it.

**Comment by walterhiggins** [comment]
_Some_ but not all modules are compatible. Basically there is no guarantee that any NPM module will work with scriptcraft if it relies on NodeJS subsystems (like fs, etc).
For example, underscore, lodash etc should work fine as they are UMD modules.

**Comment by Meldiron** [comment]
Whats the correct way to use files in this plugin? (for example settings file - settings.json)
