### ISSUE TITLE
How i can send http request?

### ISSUE THREAD

**Issue by TheRadioGuy** [walterhiggins/ScriptCraft#367]

**Comment by sgvictorino** [comment]
@DuckerMan the API documentation includes a section on the [built in `http` module](https://github.com/walterhiggins/ScriptCraft/blob/master/docs/API-Reference.md#http-module) and includes a useful [example](https://github.com/walterhiggins/ScriptCraft/blob/master/docs/API-Reference.md#example-50):

```js
var jsResponse;
var http = require('http');
http.request('http://scriptcraftjs.org/sample.json',function(responseCode, responseBody){
  jsResponse = JSON.parse( responseBody );
});
```

Hope this helped!

**Comment by TheRadioGuy** [comment]
Thanks!
Is this asynchronous in bukkit?

**Comment by walterhiggins** [comment]
It's not synchronous, that's why the callback is required.
