### ISSUE TITLE
scload("myData.json") returns null

### ISSUE THREAD

**Issue by leumasme** [walterhiggins/ScriptCraft#374]
I was trying to load some JSON-Data from a file. That didnt work because scload kept returning null.
Then i tried replicating the situation in the API-Reference: I made a file called myData.json with the example JSON data for scload in it in the plugins folder, made a new script in the same folder and put the following code in it:
```
var myData = scload("myData.json");
console.log(myData)
```
And yeah, it still logs [scriptcraft] null in the console. w h y  t h o

**Comment by leumasme** [comment]
// Sidequestion: Can you log stuff to the console without the [scriptcraft] in front?

**Comment by jonathanperret** [comment]
// Sideanswer: try ` /js server.consoleSender.sendMessage("something")`

**Comment by jonathanperret** [comment]
Also `scload` with a relative path will start looking in the server's root directory, e.g. `scload("ops.json")` should return something. Try using the full path to your JSON file.
