### ISSUE TITLE
Support for 1.13

### ISSUE THREAD

**Issue by Gloorf** [walterhiggins/ScriptCraft#384]
Minecraft 1.13 makes many changes to the engine, the main one beeing a complete rework on how blocks are stored : there is no longer a hard limit of 255 different blocks, so most of the hacks using block data to increase the number of actual blocks (like all wool blocks sharing the same ID with different blocks data).

Spigot will have a compatibility layer for most of the incompatibles changes, but we shouldn't rely on it.

Some links to read : 

https://www.spigotmc.org/threads/minecraft-1-13-what-to-expect.288714/

https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

**Comment by jonathanperret** [comment]
Duplicate of #349 ? Thanks for the links though.

**Comment by Gloorf** [comment]
Oops yes definitively, looked too fast at the existing issues :)
