### ISSUE TITLE
MASSIVE ISSUE with onTabComplete!!!

### ISSUE THREAD

**Issue by ghost** [walterhiggins/ScriptCraft#390]
ScriptCraft didn't account for 1.13's new tab completion mechanics. The game automatically provides suggestions as you type, so while you're typing away at a script, like /js jx.player.get('hbms432'), the chat will constantly SPAM the 'name cannot be empty' message (which after hours of searching, comes from a try/catch block on line 59 of ScriptCraftPlugin.java) and the console will be totally SCREWED UP with stack traces galore.

A conditional statement NEEDS to be added which prevents an error from being processed if there are no available tab completions. Either that, or some smart way to avoid the error all together.

This is a BIG PROBLEM for my server because it completely 100% relies on this plugin for EVERYTHING. My embedded discord console (thanks DiscordSRV) has been causing some issues for other operators. Namely, lag from the SHEER DELUGE of messages coming from console.

**Comment by ghost** [comment]
I managed to create a modified JAR (SleepingDragon) that fixes the issue by removing the two lines that log the error to the console and the commandSender. This however is simply a duct-tape style fix and does not really solve the underlying issue, however it might be useful for someone like it is for me. Download: https://github.com/hbms432/ScriptCraft/releases/tag/SleepingDragon

**Comment by AlexanderGriffin** [comment]
You sir, are a gentleman and a scholar. I was running into the same issue and was about to do the same thing but it appears you have beat me to it.
