### ISSUE TITLE
1.13.x - 'name cannot be empty' error when running /js functionName()

### ISSUE THREAD

**Issue by AlexanderGriffin** [walterhiggins/ScriptCraft#395]
Hello,

(Only in 1.13.x - 1.12.x works fine) 

When I run any command from in game via /js functionName(), as soon as I begin to enter the parenthesis the console is spammed with 'name cannot be empty' as well as Java errors in my server console. 

Everything else seems to be working properly. 

I will include the Java stack trace as soon as I can. Thanks!

**Comment by AlexanderGriffin** [comment]
Issue already mentioned in previous post.

**Comment by jwulf** [comment]
https://github.com/walterhiggins/ScriptCraft/issues/390
