### ISSUE TITLE
Zero-width space character breaks http.request in 3.4.0

### ISSUE THREAD

**Issue by jwulf** [walterhiggins/ScriptCraft#410]
Hi Walter, it looks the 3.4.0 release zip has an zero-width space on line 84 of `src/js/modules/http/request.js`, between `runTaskAsynchronously` and the following `(` character.

https://github.com/walterhiggins/ScriptCraft/blob/3.4.0/src/main/js/modules/http/request.js#L84

This breaks it at run-time.

Here is a screenshot with the "Gremlins tracker" for VS Code installed that highlights it:

<img width="607" alt="Screen Shot 2019-06-18 at 11 06 53 pm" src="https://user-images.githubusercontent.com/406975/59684653-cba7f600-921d-11e9-8829-ebedc470ca40.png">

This took me a loooooong time to isolate. :-)

**Comment by jwulf** [comment]
Came in via this commit by the look of it: https://github.com/walterhiggins/ScriptCraft/commit/f7601576bcc5b641b9833561c49fab9f2af4a333#diff-47988c231ed13d71f3921b8fc2f1c0a0L80

**Comment by Craaftx** [comment]
I confirm this breaks at run-time, any news ?
