### ISSUE TITLE
Things such as placing wall signs and the server.executeVanillaCommand don't work anymore.

### ISSUE THREAD

**Issue by nanocodex** [walterhiggins/ScriptCraft#417]
Are there any ways around these?

**Comment by jwulf** [comment]
I use the [magikcraft/scriptcraft](https://hub.docker.com/r/magikcraft/scriptcraft) docker image and the [@magikcraft/core](https://www.npmjs.com/package/@magikcraft/core) npm package.

With that you can do:

```
import {server} from '@magikcraft/core'

server.executeCommand('someCommand goes here')
```

See: https://github.com/Magikcraft/magikcraft-core/blob/master/server/index.ts#L25

**Comment by nanocodex** [comment]
Thanks, but what’s a docker image and an npm package? I don’t know any of those.

**Comment by nanocodex** [comment]
Can I ask you more questions on what Magikcraft is on Discord if I have any @jwulf?

**Comment by jwulf** [comment]
Sure. Also, you can try a hosted version at https://play.magikcraft.io

**Comment by nanocodex** [comment]
Thanks. :)
