### ISSUE TITLE
‘ and “ in server.dispatchCommand strings

### ISSUE THREAD

**Issue by nanocodex** [walterhiggins/ScriptCraft#422]
Is it possible to execute a server command with both the ‘ and “ symbols in the string?
Example :
`/give @p minecraft:piston{display:{Name:'{"text":"Text Here","color":"gray","underlined":true}',Lore:['[{"text":"More ","color":"dark_red","bold":false},{"text":"Text ","color":"dark_blue","strikethrough":true},{"text":"Here","color":"reset"}]']}} 1 `

**Comment by jwulf** [comment]
Yes, you choose either " or ' as your quote symbol, and then escape the other one

```
"This string's content contains a mix of \" and ' characters. The \" symbol has to be escaped with a \\ character."
```

**Comment by nanocodex** [comment]
The last time I tried doing that, it returned an error, I’ll have to try it again to see if it actually works or not.

**Comment by nanocodex** [comment]
Yep, it works.
