### ISSUE TITLE
No Javascript available (fedora)

### ISSUE THREAD

**Issue by gregja** [walterhiggins/ScriptCraft#437]
Hi,
I just installed Scriptcraft on Fedora 29.
I installed JDK 1.8.0-232 (wich includes Nashorn)
I started manually Nashorn to check it, it works fine.
I yes installed Spigot-1.15.2
When I start Spigot, I receive the message "No Javascript engine available"
and the prompt doesn't interpret JS code.
Did I omit something ? Could you help me please ?
Best regards

**Comment by Day-OS** [comment]
I was having the same problem with paper. There's a patch that fixes it. Might be able to do the job.
https://github.com/Magikcraft/MagikCraft/releases

**Comment by gregja** [comment]
Hi @Day-OS ,
Thank's a lot for you help. 
I installed MagikCraft and Spigot starts correctly now, but I have a last problem : 
when I type "/js 1+1", I receive the message : "you don't have scriptcraft.evaluate.permission"

I saw that there is an issue about that : 
https://github.com/walterhiggins/ScriptCraft/issues/48

I will try tomorrow and I will confirm if it's OK
Thank's again

**Comment by gregja** [comment]
Just to confirme that it works for me with MagickCraft. 
Following the tip of the issue https://github.com/walterhiggins/ScriptCraft/issues/48
I typed "go" followed by my user name, to elevate privileges, and I'm now able to use Javascript code.
Thank's a lot.

**Comment by gregja** [comment]
Hi,
I hope that everybody here is in good health.
I met a bug with the drone object.
My config is :
- Scriptcraft on Fedora 29.
- JDK 1.8.0-232 (wich includes Nashorn)
- Spigot-1.15.2
- MagicCraft (as recommended in that issue https://github.com/walterhiggins/ScriptCraft/issues/437)

The error is :

xxx issued server command: /js drone.box(blocks.rainbow[1])
[10:48:03 INFO]: [scriptcraft] Drone build error: java.lang.ClassCastException: Cannot cast java.lang.Double to org.bukkit.block.data.BlockData while processing function wrapperFn() { [native code] }

Simple commands like "/js var drone = new Drone(self)" seems to work fine.
Is is due to something wrong in my configuration ?
Thank's for you help.
Take care.
