### ISSUE TITLE
JS engine not found

### ISSUE THREAD

**Issue by 5mmx** [walterhiggins/ScriptCraft#442]
Hello! I tried running this today and found out that messages that say that no JS engine is found appear. 
`[scriptcraft] No JavaScript Engine available. ScriptCraft will not work without Javascript.`
How can I solve this? (Pls explain me in simple words because I'm not an expert of this stuff, thanks!)

**Comment by JewishLewish** [comment]
I have the same issue as well :(

**Comment by ghost** [comment]
This issue affects servers running 1.15.2 or later. Use this patched JAR file to fix the problem.
https://github.com/walterhiggins/ScriptCraft/files/4117267/scriptcraft.zip

**Comment by kubiGamer6000** [comment]
@hb432 thanks dude that fixed it for me

**Comment by 5mmx** [comment]
Thanks! It helped a lot!

**Comment by ajay142020** [comment]
hi i copied the file into the plugins folder.. but still getting the same issue
 [Server thread/ERROR]: [scriptcraft] No JavaScript Engine available. ScriptCraft will not work without Javascript.
I am running Java 15.0.1

> This issue affects servers running 1.15.2 or later. Use this patched JAR file to fix the problem.
> https://github.com/walterhiggins/ScriptCraft/files/4117267/scriptcraft.zip

**Comment by briangershon** [comment]
Java 15 no longer has the Nashorn JavaScript Engine -- it was deprecated at Java 11 and now removed: https://golb.hplar.ch/2020/04/java-javascript-engine.html

I was able to see this working on Java 14.x (on MacOS) and ran into this issue trying to install on a new machine.

I found more conversation about moving to Graal here: https://github.com/walterhiggins/ScriptCraft/issues/444

**Comment by ghost** [comment]
> This issue affects servers running 1.15.2 or later. Use this patched JAR file to fix the problem.
> https://github.com/walterhiggins/ScriptCraft/files/4117267/scriptcraft.zip

You are a legend even 8 months later
