### ISSUE TITLE
How to reload

### ISSUE THREAD

**Issue by edonaldson** [walterhiggins/ScriptCraft#52]
I don't see that the reload command is exposed anymore.  how do you reload JS files that you create and modify in the js_plugins directories?

For instance, I'd like to create a folder js-plugins/mine to put my own js files in as I develop and test, but I can't figure out how to get modified files to reload unless I shut down and restart the bukkit server.

In addition, if we create our own useful plugins (like a pyramid, similar to your temple, or an entire dungeon creator), do you want to know about them to include in your repository?

**Comment by mcCURS0R** [comment]
So how can the JsPlugin be reloaded without the workaround? the issue was closed must i assume that this will never be a possibility?
