### ISSUE TITLE
Add undo (transactional semantics)

### ISSUE THREAD

**Issue by nickarls** [walterhiggins/ScriptCraft#67]
Sometimes, it's nice to be able to undo stuff you built by accident. I've modified my drone.js to support stuff like

/js begin().box(1, 10, 10, 10).savepoint('foo').box(2, 20, 20, 20).rollback('foo').commit();

by adding some state in 

    var transactionBlocks = new Array();	
	var inTransaction = false;
	var savepoints = {};

some helper methods

	Drone.prototype.savepoint = function(name) {
	    if (!inTransaction) {
		    echo('Not in a transaction');
			return this;
		}
		if (typeof name == "undefined") {
			echo('No name given for savepoint');
			return this;
		}
		savepoints[name] = transactionBlocks.length;
		echo('Set savepoint ' + name + ' at ' + transactionBlocks.length);
		return this;
	}
	
	Drone.prototype.commit = function() {
		inTransaction = false;
		transactionBlocks.length = 0;
		savepoints.length = 0;
	    echo('Committed ' + transaction.length + ' blocks');
		return this;
	}
	
	Drone.prototype.begin = function() {
	    if (inTransaction) {
	      echo ('Already in a transaction');
		  return this;
	    }
	    inTransaction = true;
	    transactionBlocks.length = 0;
		savepoints.length = 0;
	    echo('Started new transaction');
		return this;
	}
	
	Drone.prototype.rollback = function(name) {
	    if (!inTransaction) {
		    echo('Not in a transaction');
			return this;
		}
		var rollbackPoint = 0;
		var rollbackCount = 0;
		
		if (! (typeof name == "undefined")) {
			if (! (name in savepoints)) {
				echo('Could not find savepoint named ' + name);
				return this;
			}
		    rollbackPoint = savepoints[name];
		}
		if (rollbackPoint > transactionBlocks.length) {
			echo('Rollbackpoint ' + name + ' is at ' + rollbackPoint + ' but there are only ' + transactionBlocks.length + ' blocks in the transaction');
			return this;
		}
		while (transactionBlocks.length > rollbackPoint) {
			var transactionBlock = transactionBlocks.pop();
            var currentBlock = this.world.getBlockAt(transactionBlock.location);
            currentBlock.setTypeIdAndData(transactionBlock.typeId, transactionBlock.data, false);
			rollbackCount++;
		}		
		echo('Rolled back ' + rollbackCount + ' blocks');
		if (rollbackPoint != 0) {
		    echo('Using savepoint ' + name + ' at ' + rollbackPoint);
		} else {
			inTransaction = false;
			savepoints.length = 0;
		}
		return this;
	}
some modifications to cuboidX

    Drone.prototype.cuboidX = function(blockType, meta, w, h, d){

        if (typeof h == "undefined")
            h = 1;
        if (typeof d == "undefined")
            d = 1;
        if (typeof w == "undefined")
            w = 1;
        var that = this;
        var dir = this.dir;
		var transactionCount = 0;

        var depthFunc = function(){
            var block = that.world.getBlockAt(that.x,that.y,that.z);
			if (inTransaction) {
                var transactionBlock = { location: block.getLocation(), data: block.getData(), typeId: block.getTypeId() };			
			    transactionBlocks.push(transactionBlock);
				transactionCount++;
			}
            block.setTypeIdAndData(blockType,meta,false);
            // wph 20130210 - dont' know if this is a bug in bukkit but for chests, 
            // the metadata is ignored (defaults to 2 - south facing)
            // only way to change data is to set it using property/bean.
            block.data = meta;
        };
        var heightFunc = function(){
            _traverse[dir].depth(that,d,depthFunc);
        };
        var widthFunc = function(){
            _traverseHeight(that,h,heightFunc);
        };

        _traverse[dir].width(that,w,widthFunc);
		if (inTransaction) {
		    echo ('Added ' + transactionCount + ' blocks to the transaction');
		}
        return this;
        
    };

and adding them to ops:

    var ops = ['up','down','left','right','fwd','back','turn',
               'chkpt','move',
               'box','box0','boxa','prism','prism0','cylinder','cylinder0','arc',
               'door','door2','sign','oak','spruce','birch','jungle',
               'rand','garden',
               'copy','paste',
			   'begin','commit','rollback','savepoint'
              ];

One known issue currently with stairs (can be found by doing a rollback() after a castle())

**Comment by nickarls** [comment]
ouch

**Comment by djMax** [comment]
+1 for this concept. Alignments confusing and unpredictable and this is one way to help

**Comment by nickarls** [comment]
Even if the patch was not accepted, it is quite easy to apply yourself
